apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 90DaysOfDevOps
  annotations:
    github.com/project-slug: Armor-test/90DaysOfDevOps
spec:
  type: other
  lifecycle: unknown
  owner: Github
